### ISSUE TITLE
WARNING cannot find gettext 0.14, and won't run gettext backward compatible test

### ISSUE THREAD

**Issue by alexandre1985** [git-l10n/git-po-helper#2]
I am using ArchLinux and running `git-po-helper` I get this warning:
```
WARNING cannot find gettext 0.14, and won't run gettext backward compatible test
```
How can I resolve this warning?

**Comment by jiangxin** [comment]
You can ignore this warning.

Because the latest version of gettext cannot find some syntax errors that gettext 0.14 may encounter, `git-po-helper` will try to find gettext 0.14 installed inside `/opt/gettext/<version>`, or `/usr/local/Cellar/gettext/<version>`.

See the following code:

 * https://github.com/git-l10n/git-po-helper/blob/master/util/prereq.go#L45-L48
